= ubuntuでのasciidocインストール手順
include::base_attributes.adoc[]

これはまえがき

== 環境

OS:: Ubuntu 20.04 LTS

== 参考文献

* link:https://itcweb.cc.affrc.go.jp/affrit/documents/guide/asciidoc/start[AsciiDoc文書作成入門 [AFFRIT Portal\]]
* https://takumon.github.io/asciidoc-syntax-quick-reference-japanese-translation/[Asciidoctor 文法クイックリファレンス(日本語訳)]
* https://wohl-yz.net/archives/1283[仕様書が書きたくなるasciidoc Markdown風にドキュメント作成 GitHub版 | 合同会社ヴォール]
* https://backport.net/blog/2018/03/03/asciidoctor_pdf_font_ja/[Asciidoctor PDFの日本語フォントを変更する | backport]
* http://www.venus.dti.ne.jp/~iisaka/DocSys/cheatsheet-ja/asciidoc-869/asciidoc-869.html[AsciiDoc チートシート]
* https://waku-take-a.github.io/asciidoctor-pdf%25E3%2581%25AB%25E3%2582%2588%25E3%2582%258BPDF%25E5%2587%25BA%25E5%258A%259B(%25E3%2583%2595%25E3%2582%25A9%25E3%2583%25B3%25E3%2583%2588).html[asciidoctor-pdfによるPDF出力(フォント): WAKU-TAKE-A  PROGRAM]
* https://waku-take-a.github.io/%25E3%2582%25B9%25E3%2582%25BF%25E3%2582%25A4%25E3%2583%25AB%25E3%2583%2595%25E3%2582%25A1%25E3%2582%25A4%25E3%2583%25AB%25E3%2581%25AB%25E3%2581%25A4%25E3%2581%2584%25E3%2581%25A6.html[スタイルファイルについて: WAKU-TAKE-A  PROGRAM]
* https://ryuta46.com/267[AsciiDoc を PDF 化する時の日本語フォントを指定する]

== 環境構築

include::develop_environment_setup.adoc[]

== メモ

=== リンク

リンクは以下のように記載する。

[source, asciidoc]
----
// 行頭の場合、またはリンクの前後に空白を入れる場合
http://www.example.com[リンク名]
// 行の途中かつリンクの前後に空白を入れない場合、
// リンクの前に"link:"を入れる
適当なテキストlink:http://www.example.com[リンク名]また適当なテキスト
----

上記はそれぞれ以下のように表示される。

http://www.example.com[リンク名]

適当なテキストlink:http://www.example.com[リンク名]また適当なテキスト

=== asciidoc記法のエスケープ

asciidoc記法で使用する記号などの前に``\``（バックスラッシュ）を入力することでエスケープできる。
たとえば``\*``（前後に空白がない場合は``pass:[**]``）で文字を囲むと**太字**になるが、``\``を直前に入力することで\**太字**と表示される。

あるいは文字列を``\pass:[文字列]``のようにpassで囲むことでもエスケープできる。

=== アイコン

``:icons: font``アトリビュートを指定すればアイコンを表示できる。

[source, asciidoc]
----
NOTE: NOTE

TIP: TIP

IMPORTANT: IMPORTANT

WARNING: WARNING

CAUTION: CAUTION
----

上記のソースでは、各アイコンの間の改行は必ず要る。ないと前の行の末尾に続くテキストになってしまう。

レンダリング結果

NOTE: NOTE

TIP: TIP

IMPORTANT: IMPORTANT

WARNING: WARNING

CAUTION: CAUTION

他にも色々なアイコンを使用できる。

icon:font[]
icon:fire[] 
icon:hand-stop-o[] 
icon:amazon[]
[aqua]#icon:twitter[]#
icon:ban[]

=== 作図

以下のように図を挿入できる。

[plantuml, test_sequence, svg, align="center"]
.PlantUMLによる作図テスト
----
Alice --> Bob: Hello
Bob --> Alice: こんにちは
----

ちなみに上記画像はsvg形式だが，png形式で図を挿入するとこんな感じ。当然だがラスタ形式なのでボケる。

[plantuml, test_component, png, align="right"]
.includeのテスト
----
include::graph_test.puml[]
----

以下のように書くことで、PlantUMLの図を挿入できる。

[source, asciidoc]
....
[plantuml, test_sequence, svg, align="center"]  # <1>
.PlantUMLによる作図テスト       # <2>
----
Alice --> Bob: Hello
----
....
<1> ``[言語, 図を画像ファイルとして保存するときのファイル名, 保存するときのファイル形式, 配置]``の順で記載する。2番め以降の要素はなくてもいい。ファイル名を指定しない場合は``<ランダムな英数字列>.png``として保存される。``align``は``left``, ``center``, ``right``から指定できる。
<2> ``.<タイトル>``で図表番号とタイトルを表示する。

画像の配置は、デフォルトでは左側になる。
``/var/lib/gems/2.7.0/gems/asciidoctor-pdf-1.6.2/data/themes/base-theme.yml``で``image_align: left``が定義されているので、画像を中央に配置するのをデフォルトにするには、独自のテーマファイルで``image_align: center``を定義すればよさそう。

タイミングチャートの線の色を信号ごとに変えるのは、需要がないのか対応しているツールが見当たらない。
どうしても線の色を変えたければ、諦めてexcelなりpowerpointなり他の作図ツールなりを使って手動で作図するしかないかもしれない。
あるいはpythonとかでタイミングチャートっぽいグラフを作図して挿入するとか。

[plantuml, timing_chart_test, svg, align="center"]
.タイミングチャートの作図テスト
----
include::timing_chart_test.puml[]
----

=== 文字色

[red]*赤色の文字* と [big red yellow-background]*はっきりとした赤色の文字* + 
[underline]*下線入りの文字* と [overline]*上線入りの文字* +
[blue line-through]*取り消し線入り青色の文字*

=== 表
 
[cols="<3,^2", options="header", width="60%"]
.表題
|====
|テキスト                         | 表示
|`\*強調*`                        | *強調*
|`\{plus}`                        | {plus}
|`\#マーカー#`                    | #マーカー#
|`[.underline]\#アンダーライン#`  | [.underline]#アンダーライン#
|====

[cols="2,2,5a"]
.表を入れ子にしてセル要素にasciidoc構文を使う
|===
|Firefox
|ブラウザ
|FirefoxはオープンソースのWEBブラウザです。

下記のような特徴があります。:

* 標準仕様準拠
* 高パフォーマンス
* 高い可搬性

http://getfirefox.com[Firefoxをダウンロードする]!

[cols="2,2,5a"]
!===
!Firefox
!ブラウザ
!FirefoxはオープンソースのWEBブラウザです。
下記のような特徴があります。:

* 標準仕様準拠
* 高パフォーマンス
* 高い可搬性

http://getfirefox.com[Firefoxをダウンロードする]
!===

|===

[cols="e,m,^,>s", width="25%"]
.整形、セル結合
|===
|1 >s|2 |3 |4
^|5 2.2+^.^|6 .3+<.>m|7
^|8
|9 2+>|10
|===

セル結合すると一気にコードが暗号めいてくる。プレビューせずにどのようにレンダリングされるのか想像するのはまず無理。

セル結合については https://qiita.com/kob58im/items/2f8a9a5a60f445b083b0[AsciiDocの表(Table)のcols属性の仕様＆Asciidoctorの内部実装について調べてみた - Qiita] が参考になる。

[appendix]
== 最初の付録

=== 最初の節

=== 次の節

[appendix]
== 次の付録
