= 環境構築
include::base_attributes.adoc[]

== rubyインストール

asciidoctor（後述）はubuntuのパッケージ管理システムにも登録されているが、RubyGem (gem)パッケージとして配布されているものを使用するのが一般的なようなので、rubyをインストールする。

ここでは簡単のためにパッケージ管理システムを使用してインストールする。
ただしlink:https://www.ruby-lang.org/ja/documentation/installation/#package-management-systems[Rubyのインストール]によると、パッケージ管理システムに登録されているバージョンは最新ではないので推奨されていない。

``sudo apt install ruby``

== asciidoctorインストール

asciidocの処理系としてデファクトスタンダードであるasciidoctorを使用する。

`sudo gem install asciidoctor asciidoctor-pdf asciidoctor-diagram`

* `asciidoctor`: HTMLに変換するのに使う
* `asciidoctor-pdf`: PDFに変換するのに使う
* `asciidoctor-diagram`: PlantUMLなどの図をレンダリングするために使うasciidoc拡張

== ソースコードのハイライト設定

ソースコードをハイライトするには、ハイライト用ツールをインストールした上で、アトリビュートを指定する必要がある。

. ハイライト用ツールをインストール: ハイライト用ツールはいくつかあるが、ここでは``rouge``をインストールする。

    sudo gem install rouge

. アトリビュートを設定: asciidocファイルに``:source-highlighter: rouge``を追加

== 文字色の設定

asciidoctor-pdfのデフォルト設定でPDFに出力すると、文字色が反映されない。
これはテーマファイルにおける``role``カテゴリーを定義することで対応する。

``:pdf-theme:``アトリビュートでテーマファイルを指定し，テーマファイルに以下のようにルールを追加する。

[source, yaml]
----
role:
  red:
    font_color: ff0000
  yellow:
    font_color: ffff00
  green:
    font_color: 008000
  aqua:
    font_color: 00ffff
  blue:
    font_color: 0000ff
  navy:
    font_color: 000080
----

テーマファイルで色のルールを設定するので、**設定していない色は使えない**ことに注意。

詳細は以下を参照。

* https://itcweb.cc.affrc.go.jp/affrit/documents/guide/asciidoc/start#%E3%82%B9%E3%82%BF%E3%82%A4%E3%83%AB%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E5%A4%89%E6%9B%B4[AsciiDoc文書作成入門 [AFFRIT Portal\]]の"リスト 42. その他の設定変更"
* https://waku-take-a.github.io/asciidoctor-pdf%25E3%2581%25AB%25E3%2582%2588%25E3%2582%258BPDF%25E5%2587%25BA%25E5%258A%259B(%25E6%2596%2587%25E5%25AD%2597%25E8%2589%25B2).html[asciidoctor-pdfによるPDF出力(文字色): WAKU-TAKE-A  PROGRAM]

デフォルトのテーマ設定ファイルは以下を参照。

* ``/var/lib/gems/2.7.0/gems/asciidoctor-pdf-1.6.2/data/themes/``
** default-with-fallback-font-theme.yml
*** ``:pdf-theme: default-with-fallback-font``を指定したときに読み込まれる様子。
** default-theme.yml
*** 上記の``default-with-fallback-font-theme.yml``はこのファイルを拡張(``extends: default``)している様子。

デフォルトのテーマファイルを作業ディレクトリにコピーして、いい感じになるように編集するのが手っ取り早いかもしれない。

== 日本語フォントを導入

https://itcweb.cc.affrc.go.jp/affrit/documents/guide/asciidoc/start#%E6%97%A5%E6%9C%AC%E8%AA%9E%E3%83%95%E3%82%A9%E3%83%B3%E3%83%88%E3%81%AE%E5%88%A9%E7%94%A8[AsciiDoc文書作成入門 [AFFRIT Portal\]]の"8. 日本語フォントの利用"を参照。
ただし、themeファイルの拡張子は``.yml``である必要がある。yaml形式だからといって``.yaml``にすると、以下のようなエラーが発生する。

....
asciidoctor: ERROR: could not locate or load the built-in pdf theme `./theme.yaml'; reverting to default theme
....

フォント設定は以下のwebページが参考になる。

* https://mochimoffu.hateblo.jp/entry/2019/09/26/003000[ドキュメント作成の話～Asciidocを使えるようにする～ - 困った時の自分用メモ]
* https://qiita.com/kuboaki/items/67774c5ebd41467b83e2[asciidoctor-pdfでかっこいいPDFを作る(1) - Qiita]
* https://github.com/asciidoctor/asciidoctor-pdf/blob/main/docs/theming-guide.adoc#custom-fonts[asciidoctor-pdf/theming-guide.adoc at main · asciidoctor/asciidoctor-pdf · GitHub]
** asciidoctor-pdf公式のテーマ設定ガイド
* https://backport.net/blog/2018/03/03/asciidoctor_pdf_font_ja/[Asciidoctor PDFの日本語フォントを変更する | backport]
* https://ryuta46.com/267[AsciiDoc を PDF 化する時の日本語フォントを指定する]
* https://wohl-yz.net/archives/1683[Docker版 仕様書が書きたくなるAsciiDoc Markdown風にドキュメント作成 | 合同会社ヴォール]

== vscodeインストール

Visual Studio Code(vscode)の拡張機能を使うと、asciidocテキストを編集したりプレビューしたりするのが簡単にできるので、ここではasciidocテキストのエディタとしてvscodeを使う。

Ubuntu Softwareからvscodeをインストールすると日本語を入力できないので、link:https://code.visualstudio.com[Visual Studio Code - Code Editing. Redefined]からdebパッケージをダウンロードしてインストールする。

== vscodeのasciidoc拡張機能をインストール

拡張機能タブで``asciidoctor.asciidoctor-vscode``を検索してインストールする。
ファイルの拡張子を``.adoc``にして保存すると、asciidocテキストのハイライトが有効になる。

vscodeの設定画面を開き、以下のとおり設定する。

* Asciidoc: Asciidoctor_command: `asciidoctor -r asciidoctor-diagram -a outdir=.asciidoctor -a imagesdir=.asciidoctor -a imagesoutdir=.asciidoctor`
* Asciidoc: Use_asciidoctor_js: チェックを外す。JavaScript版のasciidoctorを使わず、PCにインストールしたasciidoctor(Ruby版)を使う。
* Asciidoc: Use_asciidoctorpdf: チェックを入れる。PCにインストールしたasciidoctor-pdf(Ruby版)を使う。
* Asciidoc: Use Workspace Root: チェックを入れる。ワークスペースのrootパスをベースディレクトリとする。

== PlantUMLによる作図環境構築

=== javaインストール

``sudo apt install default-jdk``

ちなみに、javaソフトウェアの実行だけならJREでもいいが、あとからJDKをインストールするのが面倒なので、ここではJDKをインストールしている。

=== GraphVizインストール

`sudo apt install graphviz`

ちなみに、一部の図はPlantUMLが生成するためにGraphVizを使用しない。
GraphVizが必要になる図はlink:https://plantuml.com/ja/graphviz-dot[Test your GraphViz installation]を参照。

=== 日本語の文字化け対策

デフォルトの設定ではsvg形式で図を保存するとPDF出力したときに日本語が文字化けする。
これはPlantUMLの問題ではなく、asciidoctor-diagramが日本語を含むsvg画像を出力するときに日本語に対応したフォントを使用しないことが原因である。

asciidoctor-diagramはsvg画像のテキストのフォントに``sans-serif``を使用する。
asciidoctor-diagramのフォントは変更できないので、以下のrubyスクリプトにより``sans-serif``を日本語フォントにマッピングする。

[source, ruby, linenum]
.config.rb
----
Prawn::Svg::Font::GENERIC_CSS_FONT_MAPPING.merge!(
  # 'MigMix 1P'フォントを使用する場合
  'sans-serif' => 'MigMix 1P'
)
----

日本語フォントの設定手順は<<_日本語フォントを導入, 日本語フォントを導入>>も併せて参照すること。

asciidoctor-pdf実行時、以下のように上記ファイルをロードする。
ここでは変換元ファイルと同じ階層に``config.rb``を配置したものとする。

``$ asciidoctor-pdf -r asciidoctor-diagram -r ./config.rb hoge.adoc
``

上記手順は以下のリンクを参考にした。

* link:pass:[https://qiita.com/_Shallot_/items/0b5076c98155cb6f38a0][asciidoctor-pdfで日本語を含むSVG画像を扱う - Qiita]
** asciidocでは、URLの中に``_``で囲まれた部分があるとイタリック演算子として扱われてしまい、リンクが機能しなくなる。これを防ぐには、``\pass:[URL]``のように``pass``でURLを囲むことで記号をエスケープする。
** この記事で紹介されている、asciidocotor-pdf-cjk-kai_gen_gothicをインストールする方法は、link:https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic[現在は非推奨]であるうえ、実際に試したら最新のasciidoctor-pdfでは使えなかった。

=== 日本語の文字の間隔が詰まる現象の対策

ubuntu on WSLの環境だと，日本語の文字の間隔が詰まって見栄えが悪い。
これはwindowsとubuntu on WSLの環境でインストールされているフォントが異なるのが原因である。

PlantUMLで生成されるsvg画像のフォントには``sans-serif``が使用されるが，このフォントで日本語を表示したときの文字の間隔が，windowsとubuntu on WSLで異なる。

NOTE: <<_日本語の文字化け対策, 日本語の文字化け対策>>の方法で``sans-serif``を日本語フォントにマッピングすれば解決するかもしれない。

PlantUMLで以下のダイアグラムを生成すると，PlantUMLで使用可能なフォントの一覧が表示される。

[source, plain]
----
@startuml available_fonts
listfonts ここで指定したテキストがサンプルとして表示される
@enduml
----

下図は上記のコードにより生成した，このドキュメントを生成した環境で使用可能なフォントの一覧である。

[plantuml, available_fonts, svg]
----
@startuml available_fonts
listfonts ここで指定したテキストがサンプルとして表示される
@enduml
----

フォントを変更するには，ダイアグラム内に以下のコードを追加する。

[source, plantuml]
----
skinparam {
  defaultFontName フォント名
}
----

なお，PlantUMLでは別のファイルをインクルードすることができる。
以下の例では，``inc/color.inc``に記載された内容をインクルードする。

[source, plantuml]
----
!include inc/color.inc
----
