= 環境構築
include::base_attributes.adoc[]
// AsciiDoctorのDockerイメージの最新バージョン
:docker-asciidoctor-latest: 1.28
// Krokiコンテナがホスト側に公開するポート番号
:kroki-publish-port: 8000

AsciiDocの執筆環境を構築するには、以下の2種類の方法がある。

* ローカル環境に直接各種ソフトウェアをインストールする
* AsciiDoctorの公式から提供されているDockerイメージを使用する

[[use-docker-image-of-asciidoctor]]
== Dockerイメージを使用する

=== 環境

既にvscodeとDockerがインストール済みであるものとする。
執筆時の環境を以下に示す。

[source, bash]
----
$ code --version
1.70.0
da76f93349a72022ca4670c1b84860304616aaa2
x64

$ docker version
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:57 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:03 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

$ docker compose version
Docker Compose version v2.6.0
----

[[pull-docker-image]]
=== Dockerイメージをpull

<<docker-asciidoctor>>で最新のイメージのバージョンを確認する。
執筆時の最新バージョンは{docker-asciidoctor-latest}だった。

最新バージョンを確認したら、以下のコマンドによりDockerイメージをpullする。
`{docker-asciidoctor-latest}` の部分は上で確認したバージョンに置き換えること。

[source, bash, subs="attributes+"]
----
docker pull asciidoctor/docker-asciidoctor:{docker-asciidoctor-latest}
----

なお、AsciiDoctorのDockerイメージさえあれば、以下のようにコマンドラインでAsciiDoctorを実行することができる。

[source, bash, subs="attributes+"]
----
cd <変換するAsciiDocファイルがあるディレクトリ>
docker run \
  --rm \#<1>
  -it \#<2>
  --volume $(pwd):/documents/ \#<3>
  asciidoctor/docker-asciidoctor:{docker-asciidoctor-latest} \#<4>
  asciidoctor -r asciidoctor-diagram sample-with-diagram.adoc #<5>
----
<1> 実行後にコンテナを自動的に削除する（コンテナを残しておく必要がないため）
<2> コンテナの標準入出力をターミナルの標準入出力に接続する
<3> カレントディレクトリをコンテナの `/documents/` にマウントする。AsciiDoctorコマンドはコンテナの `/documents/` ディレクトリで実行されるため、このディレクトリにマウントする。
<4> 上でpullしたDockerイメージを指定する。
<5> AsciiDoctorを実行する。

[IMPORTANT]
====
上記のDockerイメージには"Asciidoctor Kroki"も含まれている。
しかし、この拡張機能はデフォルトでは作図するために情報を https://kroki.io に送信する。
情報をインターネット上のサーバに送信したくない場合、自前でKrokiサーバを立てる必要がある。

Krokiサーバを立てる手順は<<convert-diagram-by-kroki>>を参照。
====

=== vscodeでAsciiDocファイルを編集

vscodeの"Remote - Containers"拡張機能<<remote-containers-extension>>を使用して、コンテナ内に環境を構築する。
この拡張機能の仕組みは<<developing-inside-container>>を参照。

==== 拡張機能をインストール

拡張機能画面から以下の拡張機能をインストールする。

* Remote - Containers
* AsciiDoc

[[put-dockerfile]]
==== Dockerfileを配置

コンテナを作成するためのDockerfileを作成する。
以下の内容のDockerfileをワークスペース直下に配置する。
`{docker-asciidoctor-latest}` の部分は<<pull-docker-image>>で確認したバージョンに合わせる。

[source, dockerfile, subs="attributes+"]
.Dockerfile
----
FROM asciidoctor/docker-asciidoctor:{docker-asciidoctor-latest}
----

==== Dockerコンテナ内でワークスペースを開く

. kbd:[F1] -> "Remote-Containers: Open Folder in Container..."を選択
. ワークスペースのフォルダを選択
. ワークスペースにvscodeの設定ファイル `.devcontainer/devcontainer.json` が追加される
. <<put-dockerfile>>で作成したDockerfileを元にコンテナがビルドされる
. ビルド完了後、ワークスペースがコンテナ内で開かれる

==== 拡張機能を設定ファイルに追加

ワークスペースで有効化したい拡張機能がある場合、 `.devcontainer/devcontainer.json` の"customizations -> vscode -> extensions"に拡張機能IDを記載することで、次回起動時に自動的に拡張機能がインストールされる。

直接上記の設定ファイルを編集する代わりに、拡張機能画面で追加したい拡張機能を右クリックして"Add to devcontainer.json"を選択してもよい。

どのDockerコンテナに対しても常にインストールしたい拡張機能がある場合、<<always-installed-extensions>>に従い設定する。

[[convert-diagram-by-kroki]]
=== 作図にKrokiを使用する

[[add-docker-compose-file]]
==== Docker Composeファイルを作成

以下の内容のDocker Composeファイルをワークスペース直下に `.devcontainer/compose.yaml` として保存する。
内容は<<run-multiple-kroki-containers-together>>を元に、不要なコンテナを削除し、AsciiDoctorコンテナを追加した。

[source, yaml]
.compose.yaml
----
version: "3"
services:
  asciidoctor:
    image: asciidoctor/docker-asciidoctor:1.28
    depends_on:
      - kroki
    volumes:
      # このDockerイメージからコンテナを作成して実行すると、
      # 起動時のカレントディレクトリが"/documents"
      - ../:/documents
    # デフォルトではこのDockerイメージに
    # フォアグラウンドで実行されるプロセスがないため、
    # コンテナが自動的に終了してしまうのを防ぐ
    command: /bin/sh -c "while sleep 1000; do :; done"
  kroki:
    image: yuzutech/kroki:0.17.2
    depends_on:
      - mermaid
    environment:
      - KROKI_MERMAID_HOST=mermaid
    ports:
      - "8000:8000"
  mermaid:
    image: yuzutech/kroki-mermaid:0.17.2
    expose:
      - "8002"
----

`docker compose up --detach` で上記ファイルを読み込み、各コンテナを実行する。

[NOTE]
====
ネットには `docker compose` （ハイフンがつかない） ではなく `docker-compose` （ハイフンがつく）を使用している記事が多い。
`docker-compose` は古いバージョンのDocker Composeで使用されていたものであるため、現在は `docker compose` を使用すること。<<compose-v2-docker-compose>>
====

[[add-devcontainer-json]]
==== .devcontainer.jsonを作成

以下の内容のjsonファイルを `.devcontainer/devcontainer.json` として保存する。

[source, json]
.devcontainer.json
----
{
  "name": "AsciiDoctor",
  "dockerComposeFile": "./compose.yaml",//<1>
  "service": "asciidoctor",//<2>
  "customizations": {
    "vscode": {
      "extensions": [//<3>
        "asciidoctor.asciidoctor-vscode",
        "mhutchie.git-graph",
        "ms-azuretools.vscode-docker"
      ]
    }
  },
  "workspaceFolder": "/documents"//<4>
}
----
<1> 読み込むDocker Composeファイルを指定
<2> "dockerComposeFile"の"services"から、vscodeにアタッチするコンテナを指定
<3> コンテナ内にインストールするvscode拡張機能IDを指定
<4> "service"で指定したコンテナのディレクトリから、vscodeにアタッチするディレクトリを指定する

==== Dockerコンテナ内でワークスペースを開く

. kbd:[F1] -> "Remote-Containers: Open Folder in Container..."を選択
. ワークスペースのフォルダを選択
. <<add-docker-compose-file>>で作成したDocker Composeファイルを元にコンテナが実行される
. ビルド完了後、ワークスペースが<<add-devcontainer-json>>で指定したコンテナ内で開かれる

==== Krokiで画像を生成する

AsciiDoctor-Krokiで画像を生成するために、AsciiDocファイルのアトリビュートに以下を定義する。

[source, asciidoc]
----
// KrokiサーバのURLを指定
:kroki-server-url: http://kroki:8000 //<1>
// Krokiサーバで生成した画像の埋め込みを許可する
:allow-uri-read:
----
<1> コンテナ間の通信であるため、<<add-docker-compose-file>>でホスト側に公開するポート番号を変更していても、ここではKrokiコンテナ側のポート番号である8000を指定する。

vscodeでプレビューにKrokiで生成した画像を埋め込むために、 `settings.json` に以下を追加する。

[source, json]
.settings.json
----
{
  "asciidoc.use_kroki": true
}
----

vscodeのプレビューでは、デフォルトでは別のサーバで生成した画像はセキュリティ上の理由により表示できない。
セキュリティ設定を変更するため、 btn:[F1] -> "AsciiDoc: Change Preview Security Settings" -> "Allow insecure local content"を選択する。

コマンドラインでHTMLファイルおよびPDFファイルに変換するには、以下のように使用するライブラリに `asciidoctor-kroki` を指定する。

[source, bash]
----
asciidoctor -r asciidoctor-kroki index.adoc
asciidoctor-pdf -r asciidoctor-kroki index.adoc
----

ここまでの設定が完了していれば、下図をレンダリングすることができる。

[mermaid, abcd-flowchart]
.Mermaidによる作図例
....
sequenceDiagram
    participant Alice
    participant Bob
    Alice->>John: Hello John, how are you?
    loop Healthcheck
        John->>John: Fight against hypochondria
    end
    Note right of John: Rational thoughts <br/>prevail!
    John-->>Alice: Great!
    John->>Bob: How about you?
    Bob-->>John: Jolly good!
....

[NOTE]
====
ここまで頑張って設定したものの、下図をMermaidでレンダリングすると、文字が見切れる。

[source, asciidoc]
----
[mermaid,abcd-flowchart,svg]
....
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
....
----

このせいか、asciidoctor-pdf実行時にエラーが発生して画像を埋め込むことができない。

AsciiDoctorコンテナだけでもPlantUMLは使用できるので、KrokiコンテナでMermaidをレンダリングするのを止めて素直にPlantUMLを使用したほうがいいかもしれない。
====

== ローカル環境に直接各種ソフトウェアをインストールする

=== rubyインストール

asciidoctor（後述）はubuntuのパッケージ管理システムにも登録されているが、RubyGem (gem)パッケージとして配布されているものを使用するのが一般的なようなので、rubyをインストールする。

ここでは簡単のためにパッケージ管理システムを使用してインストールする。
ただしlink:https://www.ruby-lang.org/ja/documentation/installation/#package-management-systems[Rubyのインストール]によると、パッケージ管理システムに登録されているバージョンは最新ではないので推奨されていない。

``sudo apt install ruby``

=== asciidoctorインストール

asciidocの処理系としてデファクトスタンダードであるasciidoctorを使用する。

`sudo gem install asciidoctor asciidoctor-pdf asciidoctor-diagram`

* `asciidoctor`: HTMLに変換するのに使う
* `asciidoctor-pdf`: PDFに変換するのに使う
* `asciidoctor-diagram`: PlantUMLなどの図をレンダリングするために使うasciidoc拡張

=== ソースコードのハイライト設定

ソースコードをハイライトするには、ハイライト用ツールをインストールした上で、アトリビュートを指定する必要がある。

. ハイライト用ツールをインストール: ハイライト用ツールはいくつかあるが、ここでは``rouge``をインストールする。

    sudo gem install rouge

. アトリビュートを設定: asciidocファイルに``:source-highlighter: rouge``を追加

=== 文字色の設定

asciidoctor-pdfのデフォルト設定でPDFに出力すると、文字色が反映されない。
これはテーマファイルにおける``role``カテゴリーを定義することで対応する。

``:pdf-theme:``アトリビュートでテーマファイルを指定し，テーマファイルに以下のようにルールを追加する。

[source, yaml]
----
role:
  red:
    font_color: ff0000
  yellow:
    font_color: ffff00
  green:
    font_color: 008000
  aqua:
    font_color: 00ffff
  blue:
    font_color: 0000ff
  navy:
    font_color: 000080
----

テーマファイルで色のルールを設定するので、**設定していない色は使えない**ことに注意。

詳細は以下を参照。

* https://itcweb.cc.affrc.go.jp/affrit/documents/guide/asciidoc/start#%E3%82%B9%E3%82%BF%E3%82%A4%E3%83%AB%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E5%A4%89%E6%9B%B4[AsciiDoc文書作成入門 [AFFRIT Portal\]]の"リスト 42. その他の設定変更"
* https://waku-take-a.github.io/asciidoctor-pdf%25E3%2581%25AB%25E3%2582%2588%25E3%2582%258BPDF%25E5%2587%25BA%25E5%258A%259B(%25E6%2596%2587%25E5%25AD%2597%25E8%2589%25B2).html[asciidoctor-pdfによるPDF出力(文字色): WAKU-TAKE-A  PROGRAM]

デフォルトのテーマ設定ファイルは以下を参照。

* ``/var/lib/gems/2.7.0/gems/asciidoctor-pdf-1.6.2/data/themes/``
** default-with-fallback-font-theme.yml
*** ``:pdf-theme: default-with-fallback-font``を指定したときに読み込まれる様子。
** default-theme.yml
*** 上記の``default-with-fallback-font-theme.yml``はこのファイルを拡張(``extends: default``)している様子。

デフォルトのテーマファイルを作業ディレクトリにコピーして、いい感じになるように編集するのが手っ取り早いかもしれない。

=== 日本語フォントを導入

https://itcweb.cc.affrc.go.jp/affrit/documents/guide/asciidoc/start#%E6%97%A5%E6%9C%AC%E8%AA%9E%E3%83%95%E3%82%A9%E3%83%B3%E3%83%88%E3%81%AE%E5%88%A9%E7%94%A8[AsciiDoc文書作成入門 [AFFRIT Portal\]]の"8. 日本語フォントの利用"を参照。
ただし、themeファイルの拡張子は``.yml``である必要がある。yaml形式だからといって``.yaml``にすると、以下のようなエラーが発生する。

....
asciidoctor: ERROR: could not locate or load the built-in pdf theme `./theme.yaml'; reverting to default theme
....

フォント設定は以下のwebページが参考になる。

* https://mochimoffu.hateblo.jp/entry/2019/09/26/003000[ドキュメント作成の話～Asciidocを使えるようにする～ - 困った時の自分用メモ]
* https://qiita.com/kuboaki/items/67774c5ebd41467b83e2[asciidoctor-pdfでかっこいいPDFを作る(1) - Qiita]
* https://github.com/asciidoctor/asciidoctor-pdf/blob/main/docs/theming-guide.adoc#custom-fonts[asciidoctor-pdf/theming-guide.adoc at main · asciidoctor/asciidoctor-pdf · GitHub]
** asciidoctor-pdf公式のテーマ設定ガイド
* https://backport.net/blog/2018/03/03/asciidoctor_pdf_font_ja/[Asciidoctor PDFの日本語フォントを変更する | backport]
* https://ryuta46.com/267[AsciiDoc を PDF 化する時の日本語フォントを指定する]
* https://wohl-yz.net/archives/1683[Docker版 仕様書が書きたくなるAsciiDoc Markdown風にドキュメント作成 | 合同会社ヴォール]

=== vscodeインストール

Visual Studio Code(vscode)の拡張機能を使うと、asciidocテキストを編集したりプレビューしたりするのが簡単にできるので、ここではasciidocテキストのエディタとしてvscodeを使う。

Ubuntu Softwareからvscodeをインストールすると日本語を入力できないので、link:https://code.visualstudio.com[Visual Studio Code - Code Editing. Redefined]からdebパッケージをダウンロードしてインストールする。

=== vscodeのasciidoc拡張機能をインストール

拡張機能タブで``asciidoctor.asciidoctor-vscode``を検索してインストールする。
ファイルの拡張子を``.adoc``にして保存すると、asciidocテキストのハイライトが有効になる。

vscodeの設定画面を開き、以下のとおり設定する。

* Asciidoc: Asciidoctor_command: `asciidoctor -r asciidoctor-diagram -a outdir=.asciidoctor -a imagesdir=.asciidoctor -a imagesoutdir=.asciidoctor`
* Asciidoc: Use_asciidoctor_js: チェックを外す。JavaScript版のasciidoctorを使わず、PCにインストールしたasciidoctor(Ruby版)を使う。
* Asciidoc: Use_asciidoctorpdf: チェックを入れる。PCにインストールしたasciidoctor-pdf(Ruby版)を使う。
* Asciidoc: Use Workspace Root: チェックを入れる。ワークスペースのrootパスをベースディレクトリとする。

=== PlantUMLによる作図環境構築

==== javaインストール

``sudo apt install default-jdk``

ちなみに、javaソフトウェアの実行だけならJREでもいいが、あとからJDKをインストールするのが面倒なので、ここではJDKをインストールしている。

==== GraphVizインストール

`sudo apt install graphviz`

ちなみに、一部の図はPlantUMLが生成するためにGraphVizを使用しない。
GraphVizが必要になる図はlink:https://plantuml.com/ja/graphviz-dot[Test your GraphViz installation]を参照。

==== 日本語の文字化け対策

デフォルトの設定ではsvg形式で図を保存するとPDF出力したときに日本語が文字化けする。
これはPlantUMLの問題ではなく、asciidoctor-diagramが日本語を含むsvg画像を出力するときに日本語に対応したフォントを使用しないことが原因である。

asciidoctor-diagramはsvg画像のテキストのフォントに``sans-serif``を使用する。
asciidoctor-diagramのフォントは変更できないので、以下のrubyスクリプトにより``sans-serif``を日本語フォントにマッピングする。

[source, ruby, linenum]
.config.rb
----
Prawn::Svg::Font::GENERIC_CSS_FONT_MAPPING.merge!(
  # 'MigMix 1P'フォントを使用する場合
  'sans-serif' => 'MigMix 1P'
)
----

日本語フォントの設定手順は<<_日本語フォントを導入, 日本語フォントを導入>>も併せて参照すること。

asciidoctor-pdf実行時、以下のように上記ファイルをロードする。
ここでは変換元ファイルと同じ階層に``config.rb``を配置したものとする。

``$ asciidoctor-pdf -r asciidoctor-diagram -r ./config.rb hoge.adoc
``

上記手順は以下のリンクを参考にした。

* link:pass:[https://qiita.com/_Shallot_/items/0b5076c98155cb6f38a0][asciidoctor-pdfで日本語を含むSVG画像を扱う - Qiita]
** asciidocでは、URLの中に``_``で囲まれた部分があるとイタリック演算子として扱われてしまい、リンクが機能しなくなる。これを防ぐには、``\pass:[URL]``のように``pass``でURLを囲むことで記号をエスケープする。
** この記事で紹介されている、asciidocotor-pdf-cjk-kai_gen_gothicをインストールする方法は、link:https://github.com/chloerei/asciidoctor-pdf-cjk-kai_gen_gothic[現在は非推奨]であるうえ、実際に試したら最新のasciidoctor-pdfでは使えなかった。

==== 日本語の文字の間隔が詰まる現象の対策

ubuntu on WSLの環境だと，日本語の文字の間隔が詰まって見栄えが悪い。
これはwindowsとubuntu on WSLの環境でインストールされているフォントが異なるのが原因である。

PlantUMLで生成されるsvg画像のフォントには``sans-serif``が使用されるが，このフォントで日本語を表示したときの文字の間隔が，windowsとubuntu on WSLで異なる。

NOTE: <<_日本語の文字化け対策, 日本語の文字化け対策>>の方法で``sans-serif``を日本語フォントにマッピングすれば解決するかもしれない。

PlantUMLで以下のダイアグラムを生成すると，PlantUMLで使用可能なフォントの一覧が表示される。

[source, plain]
----
@startuml available_fonts
listfonts ここで指定したテキストがサンプルとして表示される
@enduml
----

下図は上記のコードにより生成した，このドキュメントを生成した環境で使用可能なフォントの一覧である。

[plantuml, available_fonts, svg]
----
@startuml available_fonts
listfonts ここで指定したテキストがサンプルとして表示される
@enduml
----

フォントを変更するには，ダイアグラム内に以下のコードを追加する。

[source, plantuml]
----
skinparam {
  defaultFontName フォント名
}
----

なお，PlantUMLでは別のファイルをインクルードすることができる。
以下の例では，``inc/color.inc``に記載された内容をインクルードする。

[source, plantuml]
----
!include inc/color.inc
----

[bibliography]
== 参考文献

* [[[always-installed-extensions, 1]]] https://code.visualstudio.com/docs/remote/containers#_always-installed-extensions
* [[[remote-containers-extension, 2]]] https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers
* [[[developing-inside-container, 3]]] https://code.visualstudio.com/docs/remote/containers[Developing inside a Container using Visual Studio Code Remote Development]
* [[[docker-asciidoctor, 4]]] https://hub.docker.com/r/asciidoctor/docker-asciidoctor/[asciidoctor/docker-asciidoctor - Docker Image | Docker Hub]
* [[[run-multiple-kroki-containers-together, 5]]] link:https://docs.kroki.io/kroki/setup/use-docker-or-podman/#_run_multiple_kroki_containers_together[Run multiple Kroki containers together - Using Docker or Podman :: Kroki Documentation]
* [[[compose-v2-docker-compose, 6]]] https://docs.docker.jp/compose/#compose-v2-docker-compose